# Generated by Django 3.2.10 on 2022-01-13 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.IntegerField(default=datetime.datetime(2022, 1, 13, 12, 26, 1, 384196)),
        ),
    ]
